apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: showcase
  name: showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: showcase
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
