apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ofo
  name: ofo
  namespace: production
spec:
  ports:
  - name: ofo
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ofo
  type: NodePort
status:
  loadBalancer: {}
