apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-spec-veteran
  name: pod-spec-veteran
spec:
  containers:
  - image: nginx
    name: pod-spec-veteran
    ports:
    - containerPort: 80
    volumeMounts:
    - name: mntdir
      mountPath: /mntdir
    livenessProbe:
      exec:
        command:
        - cat
        - /mntdir/zero.txt
      initialDelaySeconds: 5
      periodSeconds: 5
  initContainers:
  - name: createfile
    image: busybox
    command: ['touch', '/mntdir/zero.txt']
    volumeMounts:
    - name: mntdir
      mountPath: /mntdir
  volumes:
  - name: mntdir
    emptyDir: {}
