apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod111
  name: pod111
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: redis
    name: redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
