apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-env
  name: pod-secrets-env
spec:
  containers:
  - image: redis
    name: pod-secrets-env
    env:
     - name: TOPSECRET
       valueFrom:
         secretKeyRef:
           name: very-secret
           key: Password
status: {}
