apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secrets-file
  name: pod-secrets-file
spec:
  containers:
  - image: redis
    name: pod-secrets-file
    volumeMounts:
    - name: very-secret
      mountPath: /secrets
    resources: {}
  volumes:
  - name: very-secret
    secret:
      secretName: very-secret 
status: {}
