apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ofo
  name: ofo
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ofo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ofo
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
